### ISSUE TITLE
Suite connector exits with panic

### ISSUE THREAD

**Issue by hristobojilov** [eclipse-kanto/suite-connector#16]
The error message is `panic: close of closed channel` with this stack-trace:

goroutine 303142 [running]:
github.com/eclipse/paho%2emqtt%2egolang.(*baseToken).flowComplete(0x1736b80)
        github.com/eclipse/paho.mqtt.golang@v1.3.5/token.go:101 +0x44
github.com/eclipse/paho%2emqtt%2egolang.(*messageIds).claimID(0x11c2030, {0x3539bc, 0x1743b40}, 0x5862)
        github.com/eclipse/paho.mqtt.golang@v1.3.5/messageids.go:73 +0xbc
github.com/eclipse/paho%2emqtt%2egolang.(*client).resume(0x11c2000, 0x1, 0x1755200)
        github.com/eclipse/paho.mqtt.golang@v1.3.5/client.go:943 +0x430
github.com/eclipse/paho%2emqtt%2egolang.(*client).reconnect(0x11c2000)
        github.com/eclipse/paho.mqtt.golang@v1.3.5/client.go:353 +0x478
created by github.com/eclipse/paho%2emqtt%2egolang.(*client).internalConnLost.func1
        github.com/eclipse/paho.mqtt.golang@v1.3.5/client.go:510 +0x17

**Comment by e-grigorov** [comment]
Are there steps to reproduce?
