### ISSUE TITLE
Paho credentials provider support

### ISSUE THREAD

**Issue by hristobojilov** [eclipse-kanto/suite-connector#25]
Currently, the credentials are static i.e. if they have to be changed, the suite connector has to be reinitialized. A new credentials provider can be introduced for a dynamic change. It'll be used when the connector is going to initiate a connection to the MQTT endpoint.

An example use case, the Azure connector is going to use [SAS tokens](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-dev-guide-sas?tabs=node#sas-tokens). They are limited in time validity and have to be regenerated. This will require a credentials update where the new provider can help.

**Comment by e-grigorov** [comment]
Could you please describe the full flow about the token authentication? Currently, [Eclipse Hono MQTT adapter](https://www.eclipse.org/hono/docs/user-guide/mqtt-adapter/) doesn't support token authentication.
