### ISSUE TITLE
Discrepancy when forwarding Hono commands via Suite-Connector to local agents

### ISSUE THREAD

**Issue by Boryot** [eclipse-kanto/suite-connector#41]
In our gateway environment we have an agent application subscribing to Hono command topics via the Suite-Connector. Depending on which application is started first i.e. our agent or the Suite Connector (the local Mosquito broker is always started first) we observe a difference in the  the way how the topic are forwarded to the agent application:

When both agent and Suite-Connector are started in parallel, once a Hono command topic is received then it gets forwarded by the Suite connector without including the gateway device Id:

```
07/29/2022 16:55:19 - command///req/224301d4f26-ade1-4738-bc83-ab9458f19511/install - 1393
  Topic: namespace/gwThingId/things/live/messages/install
  Path: /features/SoftwareUpdatable/inbox/messages/install
```

But if we delay the startup of the Suite Connector by for example 2 minutes, then the received topic is forwarded with the gateway device Id included:

```
07/31/2022 19:42:35 - command//namespace:gwThingId/req/2247c2d2fae-f495-4086-ab6b-c474e1b637f2/install - 1393
  Topic: namespace/gwThingId/things/live/messages/install
  Path: /features/SoftwareUpdatable/inbox/messages/install
```

From the Suite-Conenctor logs we see no difference in how the command topic subscriptions from our agent application are forwarded by the Suite-Connector to the Hono instance.

Here the log without delay:

```
2022/07/29 16:46:53.152829  [agent]  INFO   Connected clientid=agent mqtt_url=tcp://localhost:1883 
2022/07/29 16:46:53.233828  [agent]  INFO   Adding handler handler_name=logs_bus topic=$SYS/broker/log/# 
2022/07/29 16:46:53.245827  [agent]  INFO   Starting messages router...
2022/07/29 16:46:53.291830  [agent]  INFO   Sending subscribe packet clientid=agent mqtt_url=tcp://localhost:1883 qos=0 topics=[$SYS/broker/log/#] 
2022/07/29 16:46:53.292830  [agent]  INFO   Starting handler subscriber_name=logs_bus topic=$SYS/broker/log/# 
2022/07/29 16:46:53.533828  [agent]  INFO   Adding handler handler_name=params_bus topic=edge/thing/request 
2022/07/29 16:46:53.534828  [agent]  INFO   Adding handler handler_name=commands_response_bus topic=command//+/res/#,c//+/s/# 
2022/07/29 16:46:53.534828  [agent]  INFO   Adding handler handler_name=events_bus topic=event/#,e/#,telemetry/#,t/# 
2022/07/29 16:46:53.534828  [agent]  INFO   Adding handler handler_name=commands_request_bus topic=command//+/req/# 
2022/07/29 16:46:53.604828  [agent]  INFO   Starting handler subscriber_name=params_bus topic=edge/thing/request 
2022/07/29 16:46:53.604828  [agent]  INFO   Starting handler subscriber_name=events_bus topic=event/#,e/#,telemetry/#,t/# 
2022/07/29 16:46:53.604828  [agent]  INFO   Starting handler subscriber_name=commands_response_bus topic=command//+/res/#,c//+/s/# 
2022/07/29 16:46:53.604828  [agent]  INFO   Starting handler subscriber_name=commands_request_bus topic=command//+/req/# 

2022/07/29 16:46:54.211820  [agent]  INFO   Connected clientid=GMSGkZVvH2ADmsYcQbwSzd mqtt_url=mqtts://mqtt.bosch-iot-hub.com:8883 
2022/07/29 16:46:54.211820  [agent]  INFO   Sending subscribe packet clientid=GMSGkZVvH2ADmsYcQbwSzd mqtt_url=mqtts://mqtt.bosch-iot-hub.com:8883 qos=0 topics=[command//+/req/#] 
2022/07/29 16:46:54.417821  [agent]  INFO   Subscription done clientid=GMSGkZVvH2ADmsYcQbwSzd mqtt_url=mqtts://mqtt.bosch-iot-hub.com:8883 qos=0 topics=[command//+/req/#] 
2022/07/29 16:46:54.421819  [agent]  INFO   Connected clientid=cloud mqtt_url=tcp://localhost:1883 
2022/07/29 16:46:54.421819  [agent]  INFO   Sending subscribe packet clientid=cloud mqtt_url=tcp://localhost:1883 qos=1 topics="[event/# e/# telemetry/# t/#]" 
2022/07/29 16:46:54.422819  [agent]  INFO   Subscription done clientid=cloud mqtt_url=tcp://localhost:1883 qos=1 topics="[event/# e/# telemetry/# t/#]" 
2022/07/29 16:46:54.422819  [agent]  INFO   Sending subscribe packet clientid=cloud mqtt_url=tcp://localhost:1883 qos=0 topics=[edge/thing/request] 
2022/07/29 16:46:54.423822  [agent]  INFO   Subscription done clientid=cloud mqtt_url=tcp://localhost:1883 qos=0 topics=[edge/thing/request] 
2022/07/29 16:46:54.423822  [agent]  INFO   Sending subscribe packet clientid=cloud mqtt_url=tcp://localhost:1883 qos=1 topics="[command//+/res/# c//+/s/#]" 
2022/07/29 16:46:54.423822  [agent]  INFO   Subscription done clientid=cloud mqtt_url=tcp://localhost:1883 qos=1 topics="[command//+/res/# c//+/s/#]" 

2022/07/29 16:46:54.423822  [agent]  INFO   Connection status {"connected":true,"timestamp":1659106014}
2022/07/29 16:46:54.423822  [agent]  INFO   Config parameters Config parameters {"deviceId":"namespace:gwThingId","tenantId":"t123456789_hub","policyId":"namespace:gwThingId"}
2022/07/29 16:46:54.744820  [agent]  INFO   Config parameters Config parameters {"deviceId":"namespace:gwThingId","tenantId":"t123456789_hub","policyId":"namespace:gwThingId"}
2022/07/29 16:46:54.771819  [agent]  INFO   Sending subscribe packet clientid=GMSGkZVvH2ADmsYcQbwSzd mqtt_url=mqtts://mqtt.bosch-iot-hub.com:8883 qos=0 topics=[command//namespace:gwThingId/req/#] 
2022/07/29 16:46:54.771819  [agent]  INFO   Forwarded new subscription {"clientId":"ClientAgent","timestamp":"2022-07-29T16:46:54+02:00","topicId":"c//namespace:gwThingId/q/#","topicReal":"command//namespace:gwThingId/req/#"}
2022/07/29 16:46:54.822821  [agent]  INFO   Config parameters Config parameters {"deviceId":"namespace:gwThingId","tenantId":"t123456789_hub","policyId":"namespace:gwThingId"}
```

And the log where the Suite-Connector startup is delayed by 2 minutes:

```
2022/07/31 19:36:41.775656  [agent]  INFO   Connected clientid=agent mqtt_url=tcp://localhost:1883 
2022/07/31 19:36:41.775656  [agent]  INFO   Adding handler handler_name=logs_bus topic=$SYS/broker/log/# 
2022/07/31 19:36:41.777656  [agent]  INFO   Sending subscribe packet clientid=agent mqtt_url=tcp://localhost:1883 qos=0 topics=[$SYS/broker/log/#] 
2022/07/31 19:36:41.777656  [agent]  INFO   Starting handler subscriber_name=logs_bus topic=$SYS/broker/log/# 
2022/07/31 19:36:41.782656  [agent]  INFO   Starting messages router...
2022/07/31 19:36:41.782656  [agent]  INFO   Adding handler handler_name=params_bus topic=edge/thing/request 
2022/07/31 19:36:41.782656  [agent]  INFO   Adding handler handler_name=commands_response_bus topic=command//+/res/#,c//+/s/# 
2022/07/31 19:36:41.782656  [agent]  INFO   Adding handler handler_name=events_bus topic=event/#,e/#,telemetry/#,t/# 
2022/07/31 19:36:41.782656  [agent]  INFO   Adding handler handler_name=commands_request_bus topic=command//+/req/# 
2022/07/31 19:36:41.782656  [agent]  INFO   Starting handler subscriber_name=params_bus topic=edge/thing/request 
2022/07/31 19:36:41.782656  [agent]  INFO   Starting handler subscriber_name=commands_request_bus topic=command//+/req/# 
2022/07/31 19:36:41.782656  [agent]  INFO   Starting handler subscriber_name=events_bus topic=event/#,e/#,telemetry/#,t/# 
2022/07/31 19:36:41.782656  [agent]  INFO   Starting handler subscriber_name=commands_response_bus topic=command//+/res/#,c//+/s/# 

2022/07/31 19:36:41.899670  [agent]  INFO   Connected clientid=cloud mqtt_url=tcp://localhost:1883 
2022/07/31 19:36:41.899670  [agent]  INFO   Sending subscribe packet clientid=cloud mqtt_url=tcp://localhost:1883 qos=1 topics="[event/# e/# telemetry/# t/#]" 
2022/07/31 19:36:41.899670  [agent]  INFO   Subscription done clientid=cloud mqtt_url=tcp://localhost:1883 qos=1 topics="[event/# e/# telemetry/# t/#]" 
2022/07/31 19:36:41.899670  [agent]  INFO   Sending subscribe packet clientid=cloud mqtt_url=tcp://localhost:1883 qos=0 topics=[edge/thing/request] 
2022/07/31 19:36:41.900670  [agent]  INFO   Subscription done clientid=cloud mqtt_url=tcp://localhost:1883 qos=0 topics=[edge/thing/request] 
2022/07/31 19:36:41.900670  [agent]  INFO   Sending subscribe packet clientid=cloud mqtt_url=tcp://localhost:1883 qos=1 topics="[command//+/res/# c//+/s/#]" 
2022/07/31 19:36:41.900670  [agent]  INFO   Subscription done clientid=cloud mqtt_url=tcp://localhost:1883 qos=1 topics="[command//+/res/# c//+/s/#]" 

2022/07/31 19:36:41.900670  [agent]  INFO   Connection status {"connected":true,"timestamp":1659289001}
2022/07/31 19:36:41.900670  [agent]  INFO   Config parameters {"deviceId":"namespace:gwThingId","tenantId":"t123456789_hub","policyId":"namespace:gwThingId"}
2022/07/31 19:36:41.901676  [agent]  INFO   Config parameters {"deviceId":"namespace:gwThingId","tenantId":"t123456789_hub","policyId":"namespace:gwThingId"}
2022/07/31 19:36:42.201709  [agent]  INFO   Sending subscribe packet clientid=mjqQB4drAAGRbuVabPE24N mqtt_url=mqtts://mqtt.bosch-iot-hub.com:8883 qos=0 topics=[command//namespace:gwThingId/req/#] 
2022/07/31 19:36:42.201709  [agent]  INFO   Forwarded new subscription {"clientId":"ClientAgent","timestamp":"2022-07-31T19:36:42+02:00","topicId":"c//namespace:gwThingId/q/#","topicReal":"command//namespace:gwThingId/req/#"}
2022/07/31 19:36:42.201709  [agent]  INFO   Config parameters {"deviceId":"namespace:gwThingId","tenantId":"t123456789_hub","policyId":"namespace:gwThingId"}
```

Thank you in advance!

**Comment by e-grigorov** [comment]
Thanks for the report. Some more insights:
- command///req/224301d4f26-ade1-4738-bc83-ab9458f19511/install - it seems like a command to the gateway itself.
- command//namespace:gwThingId/req/2247c2d2fae-f495-4086-ab6b-c474e1b637f2/install - it seems like a command to a device behind the gateway.

For a reference see: [Receiving Commands (authenticated Gateway)](https://www.eclipse.org/hono/docs/user-guide/mqtt-adapter/#receiving-commands-authenticated-gateway)

```
2022/07/29 16:46:54.771819  [agent]  INFO   Sending subscribe packet clientid=GMSGkZVvH2ADmsYcQbwSzd mqtt_url=mqtts://mqtt.bosch-iot-hub.com:8883 qos=0 topics=[command//namespace:gwThingId/req/#] 
2022/07/29 16:46:54.771819  [agent]  INFO   Forwarded new subscription {"clientId":"ClientAgent","timestamp":"2022-07-29T16:46:54+02:00","topicId":"c//namespace:gwThingId/q/#","topicReal":"command//namespace:gwThingId/req/#"}
```
This is a subscription for a device behind the gateway and this subscription is forwarded to Eclipse Hono. When the install command is sent, what is your target - the gateway or a device behind?

In general, suite connector doesn't change the topics but it's responsible to:
- subscribe for the gateway topics
- forward all subscriptions for the devices behind the gateway

Could you please describe your digital twin model/representation?

You can enable the debug and set this environment variable: `TRACE_TOPIC_PREFIX=command/,c/,e/`

**Comment by e-grigorov** [comment]
@37cMPvTpA3JPXA any feedback on this topic?

**Comment by Boryot** [comment]
Hi @e-grigorov and please excuse me for the delay.

On the first topic - Both received "install" commands were sent to the gateway device, and since they are generated from the exact same backend logic, the expectation is that their topics shall not differ.

On the second topic (the initial subscription for command topics) - yes, those subscriptions are for receiving commands targeting the gateway device.

The twin model is quite simple:
- On the edge side (gateway device) we have a software update agent that subscribes for software install commands that our backend service will issue on the software update feature of that gateway's twin.
- The backend side will upon request send the install command to the gateway's twin feature, so it can be forwarded through the subscription to the software update agent running on the edge device.

**Comment by hristobojilov** [comment]
I cannot reproduce this problem.

**Comment by e-grigorov** [comment]
@37cMPvTpA3JPXA as we cannot reproduce the issue, the logs will help.

In any case, based on the last shared information, I would like to dive in more details:
- suite-connector always does the subscription for the gateway device i.e. command//+/req/# as it's visible in the logs
- your software update agent does a little different subscription: command//namespace:gwThingId/req/# and this subscription is just forwarded by the suite-connector - note that this is a subscription for a device behind the gateway, that's not the gateway

Could you please check your backend logic for a potential race condition for these two subscriptions? I guess that it has to be fixed to use command//namespace:gwThingId/req/.... when it's available.

**Comment by Boryot** [comment]
Dear @e-grigorov, please find attached a debug log from two subsequent executions of the suite connector, where the difference in forwarding the MQTT topic subscriptions can be observed.
[debug.log](https://github.com/eclipse-kanto/suite-connector/files/9708118/debug.log)

Please let me know if this confirms your suspicion regarding the race-condition between both subscriptions. Thank you in advance.

Some addition information - as we are using the Bosch IoT Suite as a back-end, we asked for and got the information that during the initial session the SuiteConnector made a subscription on the topic:
`command//org.name.space:gateway-524406ef-c731-4bd0-8513-8f187cb83634/req/2247f793500-e3b2-45c2-9cda-8bc5124acff9/install`
, while on the second attempt the subscription was made on:
`command//+/req/#`

**Comment by n-deliyski** [comment]
Hono requires the command subscription format to be only one of below two
`command//+/req/#`
or
`command//<device-id>/req/#`

If both formats are applied then the second one in the time wins and is used.

Examples:
For `command//+/req/#` subscription the published topic will be
`command///req/224301d4f26-ade1-4738-bc83-ab9458f19511/install`

For `command//<device-id>/req/#` subscription  the published topic will be
`command//org.name.space:gateway-524406ef-c731-4bd0-8513-8f187cb83634/req/2247f793500-e3b2-45c2-9cda-8bc5124acff9/install`

**Comment by Boryot** [comment]
@n-deliyski thanks for the confirmation. So we should avoid mixing both formats since the one subscribing last always win.

One question - speaking of Hono we just want to filter commands send to the gateway device from commands send to devices behind that gateway. I assume it will be safe to use the following two subscriptions via the suite-connector instead:
`command///req/#`
in our edge applications listening for gateway device commands only, and:
`command//+/req/#`
in our edge applications that listen for commands on both gateway devices and "child" devices? Or is still the one or the other?

**Comment by e-grigorov** [comment]
@n-deliyski
Thanks for the details. That was the race condition that I was looking for. I am preparing a few issues for Hono project because this is not documented and somehow counter-intuitive. The expectation was that the gateway itself is acting as authenticated device but the gateway is supported as a device behind the gateway :)

In any case, we have to extend the suite-connector to support all these combinations. Do you plan any fixes in the topic support or we can go and adapt to the described behavior?

**Comment by n-deliyski** [comment]
The topic `command///req/#` used by the authenticated gateway subscription is not documented.
I have tried it and have created Hono issue for that https://github.com/eclipse-hono/hono/issues/3432.

Regarding the usage of `command//+/req/#` I think it was decided to work like this, confirmed with Hono issue https://github.com/eclipse-hono/hono/issues/3412
