### ISSUE TITLE
MQTTS support in the suite-connector's local connection

### ISSUE THREAD

**Issue by Boryot** [eclipse-kanto/suite-connector#5]
As of now the suite-connector doesn't seem to support establishing a MQTTS connection with the local MQTT broker in the current implementation:

[conenctions.go](https://github.com/eclipse-kanto/suite-connector/blob/66267f96034267af6656d00073413e78a26c1c5f/config/connections.go#L192)

It would be nice, if a support for enabling MQTTS connection can be added. Also adding the corresponding properties in the suite-connector's configuration:

- for providing the CA used to sign the certificate of the local MQTT broker
- an optional device key and certificate, for the case when using device certificate is set as mandatory on the local MQTT broker.

Thank you in advance!

**Comment by e-grigorov** [comment]
Thanks for the report. Actually, I see this as a global feature. It can be applied to all components which are connected to the local broker. In any case, I'll create new issues to cover them. About this particular one, I have some comments:

> for enabling SSL on the MQTT connection (or stay with plain, if disabled)

This can be automatically handled by the broker URL i.e. if it starts with mqtts://... then it's MQTTS. Is it enough or something else is desired? Currently, we have localAddress property which can cover this scenario.

> for setting the host and port where the local MQTT broker has been bound to listens for MQTTS connections

There is localAddress property which can do the job, host and port are part of the broker URL.

**Comment by Boryot** [comment]
I assume reusing the local_address property is a better option as you mentioned. I was mistaken since in the current implementation it start with "tcp://"

And yes, you are totally right - I forgot the fact that both port and address are supplied in the value for the local_connection property. Indeed, no need to duplicate them.

**Comment by e-grigorov** [comment]
Thanks a lot for your feedback. I'll update the issue description.
